### ISSUE TITLE
Handle network changes

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#22]
Currently, when switching networks, AutoNAT takes a while (forever?) to detect that the NAT status has changed. I wonder if we could detect this? Somehow detect IP address changes?

**Comment by vyzo** [comment]
It currently waits for 15min before re-checking status once it has determined a definite NATStatus.
We could do a more frequent check to see if the address set has changed however.

**Comment by Stebalien** [comment]
Are we sure that's working? I've tried suspending my laptop, moving to a coffee-shop, and resuming. I'm not sure if I've waited long enough but I'm pretty sure I did.

**Comment by aarshkshah1992** [comment]
@Stebalien Isn't this a duplicate of https://github.com/libp2p/go-libp2p-autonat/issues/34 ?

**Comment by Stebalien** [comment]
Hm. Yes. There are too few issues in this repo for me to claim I couldn't _find_ this issue.... I just never looked.
