### ISSUE TITLE
AutoNAT only adds AutoNAT service peers on *new* connection

### ISSUE THREAD

**Issue by paul-freeman** [libp2p/go-libp2p-autonat#28]
The AutoNAT service contains [a mapping of ID to AddrInfo](https://github.com/libp2p/go-libp2p-autonat/blob/60bf479cf6bc73c939f4db97ad711756e949e522/autonat.go#L55), but this mapping is only updated [when the host reports a new connection](https://github.com/libp2p/go-libp2p-autonat/blob/60bf479cf6bc73c939f4db97ad711756e949e522/notify.go#L36).

The issue is that the host's existing connections are not checked for AutoNAT support.

My specific issue arose when I was trying to have my relay hosts also provide AutoNAT service. Because I was bootstrapping my relay hosts into the local peer's DHT, the peer already had connections to them by the time the AutoNAT service was initialized. This meant that the list of AutoNAT peers never included the relay hosts and, thus, NAT status could not be determined.

It would seem that, at a minimum, it would be good to allow the AutoNAT to be bootstrapped with its own list of peers (this list of bootstrap peers would probably need to be provided to `EnableAutoRelay`). Although ideally, it would be better for the AutoNAT service to query existing connections from the host when it starts.

**Comment by vyzo** [comment]
We are in the process of adding a static list of relay peers that can be used instead of discovery in https://github.com/libp2p/go-libp2p/pull/705.
We also want to add passive discovery whereby relays can also be discovered by connecting to them, as reported by the circuit subsystem.

**Comment by vyzo** [comment]
Also of note, we would happily accept a patch that makes autonat check existing connections for service support.

**Comment by willscott** [comment]
autonat no longer maintains a this peer cache, and will aim to only piggyback on existing connections
