### ISSUE TITLE
Re-check our NAT status when addresses change

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#34]
Now that we have an event system, we can easily and eagerly re-check our NAT status whenever we change addresses. Relates to #11.

**Comment by aarshkshah1992** [comment]
@Stebalien @willscott 

The address change event will be emitted [here](https://github.com/libp2p/go-libp2p/blob/416a878390ed172bf5c6285b1a47740c4777d4c1/p2p/host/basic/basic_host.go#L316) . But, we don't need to wait for that PR to get merged.

I can create a PR for this if you guys like.

**Comment by aarshkshah1992** [comment]
Nevermind. I think it's being done in https://github.com/libp2p/go-libp2p-autonat/pull/41.
