### ISSUE TITLE
Don't spawn and sleep a goroutine every time we receive a connection.

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#40]
The way we're currently handling connect events (notify.go) is awful.

**Comment by aarshkshah1992** [comment]
@Stebalien @willscott 

Really, we shouldn't need to cache AutoNAT peer addresses like this at all to protect them from the wrath of disconnections/peerstore expiry. The way to do this would be:

1. Get https://github.com/libp2p/go-libp2p/issues/800 in first
2. We now subscribe to the `EvtPeerIdentificationCompleted` message on the Eventbus & if a peer supports the AutoNAT protocol, note down it's peerId so we can keep pinning it till we get an error while trying to probe it.  Once we get a dial error, we remove the peerId from our cache & Unpin it.
3. We use peerIds from our cache for probing. The addresses should be in the peerstore.

**Comment by aarshkshah1992** [comment]
@Stebalien 

Can we change the title to "Refactor how we manage AutoNAT peers" as if done right, this will also help solve #9 AND #28 . 

@jacobheun If Sir Steb agrees, we should make this a feature & add it to Working Kademlia.

**Comment by willscott** [comment]
After we note down ids's of peers supporting autonat, how do we choose which peer in that list to attempt dialing?

**Comment by Stebalien** [comment]
> Really, we shouldn't need to sleep for Identify to complete(we already have the EvtPeerIdentificationCompleted event on the bus for this)

We should use the identify event. We didn't before because it didn't exist.

> Can we change the title to "Refactor how we manage AutoNAT peers" as if done right, this will also help solve #9 AND #28 .

Let's create a new issue with a specific proposal (we can create multiple issues with different proposals). This is issue is just a bug report about a specific issue.

----

Note: IMO, in the best of all worlds, we wouldn't handle this in autonat at all. We'd just ask the peerstore "who have we seen recently that supports the autonat protocol". But that's further off.

For now, just remembering a set of peers in this service (no need to block on "pins").
