### ISSUE TITLE
Ignore potential AutoNAT servers with a private RemoteAddr

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#44]
Corollary to https://github.com/libp2p/go-libp2p-autonat-svc/issues/33, the client shouldn't even ask a peer to test its NAT status if the connection's remote address isn't routable.

**Comment by aarshkshah1992** [comment]
@Stebalien @willscott 

The best way to do this would be to not register a peer with a private RemoteMultiAddr as an AutoNAT server at all in https://github.com/libp2p/go-libp2p-autonat/blob/6f8dd31f728d5e221565bfbc5814a81b9af8dd02/notify.go#L36.
