### ISSUE TITLE
Try dialing potential AutoNAT services on private addresses

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#45]
Before trusting an AutoNAT service, we should try dialing it on all _unroutable_ addresses. We can do this by creating an ephemeral libp2p node (like the AutoNAT service does) but only feeding it unroutable addresses.

This should help tell is if the target is truely on a different network.

**Comment by willscott** [comment]
If we aren't careful, this could potentially lead to a non-trivial amount of local network connection attempts. Many nodes will have private networks in the 3 private network spaces, so we're likely to be generating an ongoing trickle of local network connection attempts from most libp2p nodes in doing this

**Comment by Stebalien** [comment]
So... we already do that, unfortunately . However, I agree we should do this as a last resort (ideally, the traceroute would handle it for us).

You may be interested in https://github.com/libp2p/go-libp2p/issues/436 and the very long discussion.

**Comment by Stebalien** [comment]
> So... we already do that, unfortunately .

Really, given that, I'd expect this to be somewhat of a non-issue. The "local" connections should always finish first, so just looking at the remote address should work in almost all cases.

Actually, given that, I'm just going to close this.
