### ISSUE TITLE
Event-based autonat checking

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-autonat#57]
Instead of using timeouts to determine when we should next try to check our NAT status, if we don't know our status:

1. Listen for identify events for new peers.
2. If the new peer supports AutoNAT try them.

And keep doing this till we find out our status.

**Comment by willscott** [comment]
should react to protocol updates rather than identify events once protocol updates are emitted reliably - per https://github.com/libp2p/go-libp2p/issues/860

**Comment by marten-seemann** [comment]
I think that's what we're doing: https://github.com/libp2p/go-libp2p-autonat/blob/f9d8855a383e8073dad4858407ad40db6c4e2f57/autonat.go#L202-L208
