### ISSUE TITLE
Don't keep re-dialing the same peer

### ISSUE THREAD

**Issue by willscott** [libp2p/go-libp2p-autonat#74]
There's a TODO that should be addressed where it isn't particularly useful to re-attempt to learn autonat status from a peer if we've recently asked them.

There are two parts of this:
* if we've asked all of our connected peers recently, we might want to reach an end state faster
* if we have many peers, we should de-prioritize those we've previously asked recently.

**Comment by willscott** [comment]
should be addressed now in #65

**Comment by marten-seemann** [comment]
@willscott Did #65 completely address this? Can we close this issue, or is there anything left to do?

**Comment by willscott** [comment]
Yes. I think it's fair to close this issue as obsolete
