### ISSUE TITLE
Offload peers supporting AutoNAT to peerstore

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-autonat#9]
Currently we store every peer we've ever seen that supports AutoNAT the `peers` map. This list only grows, thus leading to memory leak. We should only store _connected_ AutoNAT peers in memory, and offload the disconnected ones to the peerstore. This requires changes in the peerstore: https://github.com/libp2p/go-libp2p-peerstore/issues/55.

**Comment by aarshkshah1992** [comment]
An alternative solution could be https://github.com/libp2p/go-libp2p-autonat/issues/40#issuecomment-591404657

**Comment by willscott** [comment]
autonat no longer maintains its own cache separate from peerstore
